name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - name: Checking Node version
        run: node -v
      - name: Installing dependencies
        run: yarn install
      - name: Running lint
        run: yarn lint
      - name: Running unit tests
        run: yarn test
      - name: Coveralls Integration
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
